### ISSUE TITLE
run test failed

### ISSUE THREAD

**Issue by gorillaz-f** [treycordova/nativejsx#29]
It fails when running 

`
npm run test
`

as result:

```
GIBSONFENG-MB0:nativejsx fengwj$ npm run test

> nativejsx@4.2.0 test /Users/fengwj/Project/nativejsx
> standard && ./node_modules/.bin/mocha --harmony

/Users/fengwj/Project/nativejsx/test/allocator.js:1
(function (exports, require, module, __filename, __dirname) { const { assert } = require('chai')
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/fengwj/Project/nativejsx/node_modules/_mocha@2.5.3@mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/fengwj/Project/nativejsx/node_modules/_mocha@2.5.3@mocha/lib/mocha.js:217:14)
    at Mocha.run (/Users/fengwj/Project/nativejsx/node_modules/_mocha@2.5.3@mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/Users/fengwj/Project/nativejsx/node_modules/_mocha@2.5.3@mocha/bin/_mocha:404:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

And fails too when running examples

```
node examples
```

as result

```
GIBSONFENG-MB0:nativejsx fengwj$ node examples
/Users/fengwj/Project/nativejsx/source/nativejsx.js:30
  let copy = merge(
  ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/fengwj/Project/nativejsx/examples.js:1:81)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

I am not able to modify codes without testing~~

would it be repaired? thx

**Comment by gorillaz-f** [comment]
my mistake...   I fix it after update my node version...
